### ISSUE TITLE
Memory problem

### ISSUE THREAD

**Issue by mrgloom** [vadp/tilers-tools#1]
I'm tried to build tiles with command `tiler.py -z 0,19 maps/global_ortho.vrt -t maps/orthotiles` but as result it eat all the memory.

What is the proper way of call `tiler.py` ?

**Comment by vss-devel** [comment]
Perhaps the generated data set is too big at the highest zoom. If so, the question is if your source really has that level of detail.

You'd try to run the script without zoom parameter: it should generate a zoom range automatically.

BTW by supplying "-z 0,19" you're going to get only 2 zoom levels: 0 and 19. If you need to get a range of zoom levels then use "-" instead. But try automatic zoom detection first.

If your dataset is really big then you'd try to split it into some smaller parts and then merge results with tiles_merge.py.

**Comment by vss-devel** [comment]
Closing the issue as there is no way to reproduce the issue.
