### ISSUE TITLE
Too many values to unpack

### ISSUE THREAD

**Issue by trakais** [vadp/tilers-tools#2]
I used this script a long time ago and it worked then, but something must have changed, as I have python complaining now: 

`
python tiler.py /Volumes/Three/Documents/Kartes/Vesturiskas/KdWR/KdwR_J11_Lyserort_1917_400dpi.map 
INFO:root: /Volumes/Three/Documents/Kartes/Vesturiskas/KdWR/KdwR_J11_Lyserort_1917_400dpi.map : Kdwr_j11_lyserort_1917_400dpi.jpg (/Volumes/Three/Documents/Kartes/Vesturiskas/KdWR/KdwR_J11_Lyserort_1917_400dpi.jpg)
INFO:root: WGS 84, Latitude/Longitude
INFO:root: /Volumes/Three/Documents/Kartes/Vesturiskas/KdWR/KdwR_J11_Lyserort_1917_400dpi.vrt -> /Volumes/Three/Documents/Kartes/Vesturiskas/KdWR/KdwR_J11_Lyserort_1917_400dpi.zyx 
Traceback (most recent call last):
  File "tiler.py", line 181, in <module>
    main(sys.argv)
  File "tiler.py", line 175, in main
    parallel_map(process_src, flatten(res))
  File "/Users/normis/tilers-tools/tilers_tools/tiler_functions.py", line 97, in parallel_map
    return map(func, iterable)
  File "tiler.py", line 66, in process_src
    prm.generate_tiles()
  File "/Users/normis/tilers-tools/tilers_tools/tiler_backend.py", line 696, in generate_tiles
    self.create_target_dataset()
  File "/Users/normis/tilers-tools/tilers_tools/tiler_backend.py", line 524, in create_target_dataset
    base_ds = self.create_warped_vrt(top_left_coord, res, size)
  File "/Users/normis/tilers-tools/tilers_tools/tiler_backend.py", line 545, in create_warped_vrt
    ok, src_igeotr = gdal.InvGeoTransform(src_geotr)
ValueError: too many values to unpack
`

python --version
Python 2.7.10

**Comment by trakais** [comment]
Sorry, my mistake. Reinstalling the GDAL-complete package from Kyngchaos on OSX fixed the issue. Maybe it needs GDAL 1.11 not 2.0

**Comment by vss-devel** [comment]
Happy to hear that someone is still using it. 

Cheers! 
Vadim

**Comment by alex-mazzariol** [comment]
Thanks for mentioning the GDAL 1.11 version in the issue... I was about to open a new one.

Any plans on updating tilers-tools to make use of GDAL 2's python bindings?

**Comment by vss-devel** [comment]
No plans so far for GDAL 2, sorry.

I've updated README.

**Comment by Skippern** [comment]
I am struggling with the same problem, and since I have other services/software requiring GDAL 2, ending up with an unsolvable conflict, I have to upgrade all packages to GDAL2 when running some apps/scripts, and downgrade to GDAL 1 to run this. GDAL2 bindings would make this less of a headache for me.

**Comment by vss-devel** [comment]
Perhaps it's a bit late, but it looks that it works now with GDAL 2.
